import { AquaticItem } from './types';

export const sampleData: AquaticItem[] = [
  { id: '1', name: 'Nannostomus Cenepa', price: 'RM123' },
  { id: '2', name: 'Gastrodremus C123', price: 'RM56' },
  { id: '3', name: 'Corydoras Reticulatus', price: 'RM53' },
  { id: '4', name: 'Moenkhausia Kogal Platinum', price: 'RM78' },
  { id: '5', name: 'Hyphessobrycon Notidanos Yellow', price: 'RM75' },
  { id: '6', name: 'Hyphessobrycon Puegottei Male', price: 'RM70' },
  { id: '7', name: 'Moenkhausia Rubra Platinum', price: 'RM98' },
  { id: '8', name: 'Hyphessobrycon Cyanotaenia Yellow Platinum', price: 'RM88' },
  { id: '9', name: 'Parotocinclus HaroldoI', price: 'RM77' },
  { id: '10', name: 'Hisonotus Vireo', price: 'RM65' },
  { id: '11', name: 'Corydoras Pulwartzi', price: 'RM195' },
  { id: '12', name: 'Pterophyllum San Felipe 3-5cm', price: 'RM91' },
  { id: '13', name: 'Pterophyllum San Felipe 2-3cm', price: 'RM84' },
  { id: '14', name: 'Pterophyllum Heikon 3-5cm', price: 'RM81' },
  { id: '15', name: 'Pterophyllum Altum 2-3cm', price: 'RM98' },
  { id: '16', name: 'BEC', price: 'RM1260' },
  { id: '17', name: 'Corydoras Hastatus', price: 'RM29' },
  { id: '18', name: 'Corydoras Froehlichi', price: 'RM210' },
  { id: '19', name: 'Corydoras CW162', price: 'RM350' },
  { id: '20', name: 'Corydoras Knaacki', price: 'RM350' },
  { id: '21', name: 'Corydoras C68', price: 'RM244' },
  { id: '22', name: 'Moenkhausia Bellasonmosa', price: 'RM144' },
  { id: '23', name: 'Moenkhausia Empress', price: 'RM84' },
  { id: '24', name: 'Hemmigramus Vinaceus', price: 'RM54' },
  { id: '25', name: 'Otocinclus Flexilis', price: 'RM66' },
  { id: '26', name: 'Hypancistrus L236', price: 'RM830' },
  { id: '27', name: 'Ancistrus L144 SR', price: 'RM250' },
  { id: '28', name: 'Ancistrus L144 Green Dragon', price: 'RM350' },
  { id: '29', name: 'Gymnogeophagus Lipokarenos', price: 'RM525' },
  { id: '30', name: 'Geophagus Proximus', price: 'RM88' }
];